name: "Labeler"
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run labeler
        uses: ./github/actions/labeler
        with:
          config-path: ".github/labeler.yml"
          repo-token: ${{secrets.GITHUB_TOKEN}}
